letters = {
	a = {
		{false, false, false},
		{false, false, false},
		{false, true , true },
		{true,  false, true },
		{true,  true,  true },
	},
	b = {
		{true,  false, false},
		{true,  false, false},
		{true,  true , true },
		{true,  false, true },
		{true,  true,  true },
	},
	c = {
		{false, false, false},
		{false, false, false},
		{true,  true , true },
		{true,  false, false},
		{true,  true,  true },
	},
	d = {
		{false, false, true },
		{false, false, true },
		{true,  true , true },
		{true,  false, true },
		{true,  true,  true },
	},
	e = {
		{false, false, false},
		{true,  true,  true },
		--{true,  false, false},
		{true,  true , true },
		{true,  false, false},
		{true,  true,  true },
	},
	f = {
		{true,  true,  true },
		{true,  false, false},
		{true,  true , true },
		{true,  false, false},
		{true,  false, false},
	},
	g = {
		{false, false, true },
		{true,  true , true },
		{true,  true , true },
		{false, false, true },
		{true,  true,  true },
	},
	h = {
		{true,  false, false},
		{true,  false, false},
		{true,  true , true },
		{true,  false, true },
		{true,  false, true },
	},
	i = {
		{true },
		{false},
		{true },
		{true },
		{true },
	},
	j = {
		{false, true },
		{false, false},
		{false, true },
		{false, true },
		{true , false},
	},
	k = {
		{true,  false, false},
		{true,  false, false},
		{true,  true , true },
		{true,  true,  false},
		{true,  false, true },
	},
	l = {
		{true , false},
		{true , false},
		{true , false},
		{true , false},
		{true , true },
	},
	n = {
		{false, false, false},
		{false, false, false},
		{true,  true , true },
		{true,  false, true },
		{true,  false, true },
	},
	m = {
		{false, false, false, false, false},
		{false, false, false, false, false},
		{true,  true , true,  true , true },
		{true,  false, true,  false, true },
		{true,  false, true,  false, true },
	},
	o = {
		{false, false, false},
		{false, false, false},
		{true,  true , true },
		{true,  false, true },
		{true,  true,  true },
	},
	p = {
		{false, false, false},
		{true,  true,  true },
		{true,  false, true },
		{true,  true , true },
		--{true,  false, false},
		{true,  false, false},
	},
	q = {
		{true,  true,  true },
		{true,  false, true },
		{true,  true , true },
		{false, false, true },
		{false, false, true },
	},
	r = {
		{false, false, false},
		{false, false, false},
		{true,  true , true },
		{true,  false, false},
		{true,  false, false},
	},
	s = {
		{false, false, false},
		{false, false, false},
		{false, true,  true },
		{false, true,  false},
		{true,  true,  false},
	},
	t = {
		{false, false, false},
		{false, false, false},
		{true,  true , true },
		{false, true,  false},
		{false, true,  false},
	},
	u = {
		{false, false, false},
		{false, false, false},
		{true,  false, true },
		{true,  false, true },
		{true,  true,  true },
	},
	v = {
		{false, false, false},
		{false, false, false},
		{true,  false, true },
		{true,  false, true },
		{false, true,  false},
	},
	w = {
		{false, false, false, false, false},
		{false, false, false, false, false},
		{true,  false, true,  false, true },
		{true,  false, true,  false, true },
		{false, true , false, true , false},
	},
	x = {
		{false, false, false},
		{false, false, false},
		{true,  false, true },
		{false, true,  false},
		{true,  false, true },
	},
	y = {
		{false, false, false},
		{false, false, false},
		{true,  false, true },
		{true,  true,  true },
		{false, true,  false},
	},
	z = {
		{false, false, false},
		{false, false, false},
		{true,  true,  false},
		{false, true,  false},
		{false, true,  true },
	},
}
